apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: alpine-base
    spec:
      containers:
        - name: alpine-base
          image: alpine-base
          imagePullPolicy: Never
